main: xyz.acrylicstyle.storageBox.StorageBoxPlugin
name: StorageBox
version: 0.0.1-SNAPSHOT
api-version: "1.15"
author: acrylic-style
depend:
  - TomeitoLib
commands:
  storagebox:
    aliases: ["sb", "storage"]
